# Prod environment
variables:

  # Global
  ap_vm_image: ubuntu-20.04

  namespace: demo_workspace # Updated namespace
  postfix: 001 # Updated postfix
  location: eastus # Updated location

  environment: prod
  enable_aml_computecluster: true
  enable_aml_secure_workspace: true
  enable_monitoring: false

  # Azure DevOps
  ado_service_connection_rg: Azure-ARM-Prod
  ado_service_connection_aml_ws: Azure-ARM-Prod

  # DO NOT TOUCH

  # For pipeline reference
  resource_group: azure-test-int
  aml_workspace: azure-int
  application_insights: azureint1476157782
  key_vault: azureint8296069636
  container_registry: 698910f0590446db85afb7e41496fcf2
  storage_account: azureint8124552115
  
  # # For terraform reference
  # terraform_version: 0.14.7
  # terraform_workingdir: infrastructure
  # terraform_st_resource_group: rg-$(namespace)-$(postfix)$(environment)-tf
  # terraform_st_location: $(location)
  # terraform_st_storage_account: st$(namespace)$(postfix)$(environment)tf
  # terraform_st_container_name: default
  # terraform_st_key: mlops-tab
